### ISSUE TITLE
Create embeddable map showing groups by default, with a toggle to show people instead

### ISSUE THREAD

**Issue by tog22** [tog22/eahub#1]

**Comment by tog22** [comment]
As requested for/by other major EA sites.

**Comment by tog22** [comment]
OK, as requested by Maia, here's the steps:

1) Create a fresh, empty HTML file (hosted wherever, e.g. on your local computer)
2) Copy over the bare essentials of the code from http://effectivealtruismhub.com/map
3) Tell Tom/everyone in this issue because you'll already have finished the first useful end goal
4) Add a toggle interface icon that (presumably via JavaScript) toggles whether groups or people are shown

**Comment by tog22** [comment]
Maia was busy with a job hunt and one of the sites needed it done, so I just did the basic version of this without the toggle in commit https://github.com/tog22/eahub/commit/66dc095352e79d80de75c7124f110272756608cf by adding this page, embeddable in an iframe:

https://github.com/tog22/eahub/blob/master/sites/effectivealtruismhub.com/scripts/for-external-sites/ea-groups-map-embeddable.php

**Comment by haryshwaran** [comment]
Added controls to toggle between individuals and groups.
The code shown below has to be added to the php file after individual-locations.json is generated at the server side.
`window.individualsData = <?php include 'individual-locations.json';?>;`

Issue can be closed once the individuals json file is generated and included.

**Comment by tog22** [comment]
individuals json file is generated and included. And I've deployed this to the live site - closing! Beautiful toggle btw, you should see your work appear on major EA websites soon.
