### ISSUE TITLE
Modify Drupal Views code to always show profile fields from the same user together

### ISSUE THREAD

**Issue by tog22** [tog22/eahub#16]
The issue is that this doesn't happen when the fields are under separate 'profiles' (sections, like 'Donations' and 'You and EA') at http://effectivealtruismhub.com/admin/structure/profiles . For an example of what goes wrong, see http://effectivealtruismhub.com/user/profiles/offers . (If someone'd like to write a better description of this issue that'd be great!)

This would be a big contribution to the Drupal community too. There's bound to be ample discussion of it on drupal.org, especially the issue queues for the Views and Profile 2 modules, so I'd start by searching there.

I can expand on all this if someone's prepared to commit to doing a fair bit of work on this.

**Comment by william-r-s** [comment]
I think I figured out how to do this in (at least for the offers page: http://prntscr.com/8370s1). Under Format/Format/Settings on the view edit page, there's a spot to select a grouping field (you also need to hide the grouping field you use by using the Exclude from Display option under the field settings in Fields). Does this solve the issue you were thinking about?

**Comment by tog22** [comment]
Applied this (well found) fix to the live site: http://effectivealtruismhub.com/user/profiles/offers
