### ISSUE TITLE
Add advanced search for EA Profiles: search by at least some common fields

### ISSUE THREAD

**Issue by tog22** [tog22/eahub#21]
@wrsaunde said:

> Are there any other profile fields it would make sense to search by? If so, it's possible to set up through search api (but I haven't seen a nice way to do a fully general search, ie. have a dropdown of all fields and choose which to search by)

I of course said "yeah definitely" - plus "would you be ok to make a suggested list, say in a gdoc, and put it here [initially meaning #p-eahub on Slack, though github might be better] for comment?" So I'm assigning this to him, at least for now! :smile:

**Comment by william-r-s** [comment]
I did a quick scan through the fields to see if anything stuck out as being useful. Overall, I'm not sure how useful of a feature this actually is (and it will probably clutter up the search UI if we add too much). It might be best to wait for specific feature requests from users, and implement only then.

It seems like it might useful to search by organization support and by cause.

There are two fields to searh by organization:
Groups you're a member of (field_which_of_the_following_gro)
Organisations you've volunteered or worked for (field_have_you_volunteered)

There are 3 different fields about cause selection, I'm not sure which of them would be the best to use:
To which causes? (field_if_so_to_which_causes_)
Causes you think you should devote resources to (field_which_of_the_following_cau)
Causes and communities you're interested in (field_interest_in_causes_and_com)

I also noticed the field "Might you be able to let EAs stay with you at the moment?" which might be best to spin out into its own page.

Let me know if there any of these you want to try adding to the search page, and I will put them in.

**Comment by tog22** [comment]
> I did a quick scan through the fields to see if anything stuck out as being useful. Overall, I'm not sure how useful of a feature this actually is (and it will probably clutter up the search UI if we add too much).

Seems reasonable, and indeed that's what I've said to the few users/organisations who've requested this. We want to focus on valuable stuff, though anything volunteers can add to the hub site contibutes to building it up :smile: 

Of the ones you mentioned I'd only add searches for:
- Causes and communities you're interested in (field_interest_in_causes_and_com)
- To which causes? (field_if_so_to_which_causes_)
- Groups you're a member of (field_which_of_the_following_gro)

> I also noticed the field "Might you be able to let EAs stay with you at the moment?" which might be best to spin out into its own page.

Already exists: http://effectivealtruismhub.com/map/people/might-be-able-to-put-up-eas . The link at http://effectivealtruismhub.com/map is very missable though, and you're always welcome to send a description/local-copy-screenshot of a suggestion you'd suggest we make live, which we'll default to doing!

**Comment by william-r-s** [comment]
I figured this out on my local version. I played around with creating a page that lists all of the fields in a table. While it's a little cluttered, it also might be useful for someone who wants to find people interested in a particular cause area. I also think it's best to use just one search box for all the fields.

Screenshot http://prntscr.com/8qcjol

Shall I go ahead and launch this as a seperate search page (Search by Causes and Groups)?

**Comment by tog22** [comment]
Yep, go for it!

**Comment by william-r-s** [comment]
I actually figured out a better way to do this! It is in fact possible to do keyword search over all profile fields. I have a version of the page up at http://eahub.org/user/profiles/searchallfields (but not linked to anywhere on the site yet). Take a peek at it and let me know if it would work to launch instead of the specialized page.

**Comment by tog22** [comment]
Thanks @wrsaunde, that looks just great. Could you edit http://eahub.org/user/profiles & http://eahub.org/user/profiles/search & http://eahub.org/user/profiles/searchallfields appropriately so that users can easily find the search functionality, then mark this issue as closed?

**Comment by william-r-s** [comment]
I made profiles/search into a page that lets you search by name or by profile contents, and the search profiles button now points to it.

**Comment by tog22** [comment]
Perfect. :) It was great to be able to spend so little time on this and
just let you work out the (clearly best!) solution.
