### ISSUE TITLE
Add vagrant (or similar) option for setting up a local copy

### ISSUE THREAD

**Issue by tog22** [tog22/eahub#24]

**Comment by tog22** [comment]
From a conversation with @wrsaunde :

William Saunders [7:17 PM]
actually, now that I think about it, do you think it would be worthwhile for me to play around and see if I can set up a vagrant environment or something similar to smooth out the local install process? I haven't really used vagrant before, but I think this is the problem it's supposed to solve

Tom Ash [7:18 PM] 
that'd definitely be somewhat valuable. depends how long it takes obviously.

Tom Ash [7:18 PM]
i'll leave it up to you

William Saunders [7:18 PM] 
k

Tom Ash [7:18 PM] 
i'd just advise being prepared to abandon it if it takes too long :simple_smile:

Tom Ash [7:19 PM]
we use vagrant for the EA Forum

Tom Ash [7:19 PM]
and it works fine

Tom Ash [7:19 PM]
but unlike the EA Forum, Drupal works fine on any standard AMP stack

**Comment by tog22** [comment]
@haryshwaran and @OAGr were also interested in this

**Comment by patbl** [comment]
@haryshwaran looks like this is done?

**Comment by haryshwaran** [comment]
yes, its done! closing this.
