### ISSUE TITLE
Fix reported error when changing profile pic

### ISSUE THREAD

**Issue by tog22** [tog22/eahub#25]
Report from konrad.seifert@t-online.de : 

> Hey guys,
> 
> when I try to change the picture and click save on the bottom, I always get
> the message, that my e-mail address is already taken (surpise, surprise!).
> There seems to be a problem with the save button also assuming that I would
> like to change my e-mail. Or am I simply too blind to find the extra button
> for the picture save?
> 
> Love for everything you do,
> Konrad

**Comment by tog22** [comment]
@patbl - up for taking a look at what's going on here?

**Comment by patbl** [comment]
I've been having difficulty setting up my development environment.

**Comment by patbl** [comment]
Konrad has a duplicate profile:

http://effectivealtruismhub.com/user/konrad
http://effectivealtruismhub.com/user/konrad-seifert

We should add a uniqueness constraint to the e-mail database column. In addition, we should remove the uniqueness constraint from the name column, since it's quite possible for two people to have the same name.

**Comment by patbl** [comment]
There are thirty users in my copy of the database that have duplicate e-mail addresses.

`SELECT mail, count(*) FROM users GROUP BY mail HAVING count(*) > 1;`

**Comment by patbl** [comment]
I don't think there's a way of altering an index to make it unique or non-unique. But removing and re-adding the indexes should work.

```
ALTER TABLE users
DROP INDEX name;

ALTER TABLE users
ADD INDEX name;
```

For e-mail addresses, we'll first have to merge the thirty duplicate accounts. Then we can do this:

```
ALTER TABLE users
DROP INDEX email;

ALTER TABLE users
ADD UNIQUE INDEX email;
```

**Comment by tog22** [comment]
Thanks for looking into this @patbl ! I'm surprised the email column didn't have a uniqueness constraint - I expect what's happened is that Drupal checks for email uniqueness when accounts are registered directly on the site, but I've been importing accounts without this getting checked. I'll get someone to sort that out in https://github.com/tog22/eahub/issues/28 . I'll reply about this issue specifically and Konrad's picture later.

**Comment by tog22** [comment]
@patbl - we've now deleted the duplicate profile, so this issue is fixed. i'll email konrad. thanks for working it out!
