### ISSUE TITLE
Fix map being broken

### ISSUE THREAD

**Issue by tog22** [tog22/eahub#27]

**Comment by tog22** [comment]
Resources I shared in our hangout:
- map: http://effectivealtruismhub.com/map
- manual steps VA follows: https://docs.google.com/document/d/1fcv6WLS7HUq5-IrFb8sUODmiDAtPvKxGuR8iumgZO3E/edit#heading=h.kt5x02ky3myh
- check quota usage: https://console.developers.google.com/project/ea-hub/apiui/apiview/geocoding_backend/usage?duration=P1D

**Comment by haryshwaran** [comment]
Creating a module for the map instead of having it as raw html in the drupal pages. This keeps the codebase visible.

**Comment by tog22** [comment]
@haryshwaran - is this issue ready for you to close after you regenerated the json?

**Comment by haryshwaran** [comment]
This issue can be closed
