### ISSUE TITLE
[MOVED] Create list of tasks to automate things that are currently done manually

### ISSUE THREAD

**Issue by tog22** [tog22/eahub#3]
This breaks down into many tasks. They could generally be done simply. One extra simple approach would be to write any sort of script which pulls data (e.g. form submissions) directly from the database, and generates a .txt file that can be included on a page with a PHP include (or, slightly neater, a Drupal filter if you're happy to learn these).

Here are some subtasks so far:
- #17 - Automate updates of map based on people's EA Profile locations

**Comment by peterhurford** [comment]
Yeah, we should brainstorm this and then split it up into individual tasks.

**Comment by tog22** [comment]
Will do

**Comment by tog22** [comment]
Here's the first subtask: #17

**Comment by tog22** [comment]
We're now handling this in Asana, and @haryshwaran has a good grasp of it.
