### ISSUE TITLE
Add complete Drupal codebase to github

### ISSUE THREAD

**Issue by tog22** [tog22/eahub#4]
Except MySQL passwords - could easily handle with an include file in ~/confidential-docroot/

**Comment by peterhurford** [comment]
:+1: Sounds like a good idea. You can reference private files that don't go on GitHub using a [.gitignore](http://git-scm.com/docs/gitignore) file in the root directory.

**Comment by tog22** [comment]
Good to know, though I'm worried that file could get lost. Whoever does this could find the best approach, as I bet Drupal is well set up for this with its multisite architecture. Alternatively they could just provide instructions to:
- Install to vhost.localhost
- Create a settings.php file in ./sites/vhost.localhost either manually or via the install script.
- Import the sample database into whatever local database this points at.

This'd probably be all that's worth doing.

**Comment by cdc482** [comment]
I'm going to work on this, as corporateclean belongs in the themes common folder

**Comment by tog22** [comment]
Awesome, could you add just the theme to github to start with? Let @arichard4 know when you're done - though both you guys can work outside github if you like.

I'll let you decide but I'd suggest creating a /sites/ folder in the root level of the github repo with _some_ of what's in /sites/ on the server\* putting it in github-repo/sites/effectivealtruismhub.com/themes/ 

\* = non-sensitive stuff, excluding anything which includes the MySQL password until you can replace this with "include "/confidential-docroot/include-files/sql-login-for-eahub.php;". This would be a good thing for you to do as part of this issue. Here are the files to do it for:

$ grep -irl "[database password - retracted for github]" ~/html/d7/sites/
/home1/sant0317/html/d7/sites/effectivealtruismhub.com/dev/past-donations.php
/home1/sant0317/html/d7/sites/effectivealtruismhub.com/settings.php
/home1/sant0317/html/d7/sites/effectivealtruismhub.com/scripts/map-exports/groups.php
/home1/sant0317/html/d7/sites/effectivealtruismhub.com/scripts/map-exports/ea-profiles.php
/home1/sant0317/html/d7/sites/effectivealtruismhub.com/scripts/map-exports/groups-gwwc.php
/home1/sant0317/html/d7/sites/effectivealtruismhub.com/modules/donation_register/donation_register.module

**Comment by tog22** [comment]
@cdc482 you may find Acquia Dev Desktop software worth trying for you own development. That's only partially and optionally related to this issue.

**Comment by tog22** [comment]
I did a bit of this in commit https://github.com/tog22/eahub/commit/66dc095352e79d80de75c7124f110272756608cf . I added the theme, some images, and a couple of scripts.

**Comment by tog22** [comment]
I did a bunch more in commit https://github.com/tog22/eahub/commit/f7ae2460983ded2893c7354db46afb1d487a4929 . @wrsaunde is now going to try and do a bit more :smile:

**Comment by william-r-s** [comment]
I believe the entire codebase is present as of https://github.com/tog22/eahub/commit/f5a7297f42e83490093e853762774359ce4d4988 (at least, I have a local installation which seems to be functioning properly).

**Comment by tog22** [comment]
Seems to be!

**Comment by peterhurford** [comment]
Excellent! :+1:
