### ISSUE TITLE
Ex. Add padding to all causes drop down on EA Donation Registry

### ISSUE THREAD

**Issue by cdc482** [tog22/eahub#5]
/donations

**Comment by tog22** [comment]
What it should look like (though feel free to change):

![screen shot 2015-06-15 at 17 41 08](https://cloud.githubusercontent.com/assets/888877/8173658/cb302ece-1385-11e5-9d2a-037c6399129a.png)

**Comment by cdc482** [comment]
Tom, this is done.  Not really happy with the display though...looking into the css. I think we need to change the type or class...

**Comment by peterhurford** [comment]
@cdc482 @tog22 Is there a PR for this?

**Comment by tog22** [comment]
The relevant CSS isn't actually in github atm - I (or Chris) still need to
do https://github.com/tog22/eahub/issues/4

**Comment by peterhurford** [comment]
I see; thanks.

**Comment by cdc482** [comment]
Done! Turns out it's a browser issue, not a CSS issue. Styling select elements inside other elements seems to frustrate lots of web developers for this reason. Anyway, in case you ever run into this again, theirs a really handy attribute for select elements---style:"width:100%;max-width:90%". Obviously you could probably think of several other fixes involving changing css files (or even javascript and php apparently), but this is definitely the "cleanest" fix. Was it worth spending all day on such a minor issue? Probably not, but I learned a lot. And at least I got something done today...pending your approval Tom.

**Comment by peterhurford** [comment]
Awesome; thanks for the hard work @cdc482 !

**Comment by tog22** [comment]
Approved in the email thread.

**Comment by peterhurford** [comment]
@tog22 should we close this issue?

**Comment by cdc482** [comment]
I have a little more work to do, based on the email. Ill close it tonight
(hopefully).

**Comment by cdc482** [comment]
Actually, it turns out that---like the original issue--the issue of the submit button dropping to the next line upon narrowing the window has many "quick" fixes changing css file(s) (apparently javascript and php code can do the same), but I'm not convinced that they are good fixes. I'm going to create a new task for that issue, so that I can spend the time needed to thoroughly research it and (hopefully) find a simple solution.

**Comment by tog22** [comment]
A quick fix would be fine given other priorities, though it's ultimately up to you :smile:
