### ISSUE TITLE
Add basic search for EA Profiles: just search by name

### ISSUE THREAD

**Issue by tog22** [tog22/eahub#9]
Could do easily through Drupal Views or Google search. Former may be better.

**Comment by william-r-s** [comment]
Looks like this can be done through Search Api (
http://www.webwash.net/tutorials/intro-search-api-part-1-how-create-search-pages ) There's a problem with displaying profile pictures though (described at https://www.drupal.org/node/1571802), I'm playing around with my local copy to get the configuration right.

**Comment by tog22** [comment]
Well found! Remember the 80-20 rule - pictures are pretty valuable, but we can live without them if that lets you implement this sooner and move onto other things.

**Comment by tog22** [comment]
(This is more saying you should make your own judgement than 'telling' you to leave pictures aside - like I say, they are pretty valuable for both aesthetics and recognisability. They're the main thing which stop the site looking too dry. :art: )

**Comment by william-r-s** [comment]
https://github.com/tog22/eahub/commit/021d4abd4cb5d56f64f0c0384a28fd0af9a1daab
Committed files required for this to repository. Some additional configuration (setting up the search index) required. @tog22, let me know when you've added the new modules, and I can set this up on the live site.

**Comment by tog22** [comment]
I've added all the files in /sites/, though not /views/ea_profiles_search.viewsexport because I'm only really updating /sites/ and there's no point adding it to the server - you can just import or recreate it in the admin interface. :smile: Go ahead and set it up on the live site and then close this issue, I've made your 'William Saunders' account an admin.

**Comment by tog22** [comment]
The final step on _this_ basic version of search (for names only) is, of course, to get it ready to launch and then launch it. This would involve suggesting places to link to it on the site, e.g. at http://dev.effectivealtruismhub.com/user/profiles and then adding those links. @wrsaunde kindly said he'd do this, though understandably "might not get to that this week, probably the week after".

He also said:

> Are there any other profile fields it would make sense to search by? If so, it's possible to set up through search api (but I haven't seen a nice way to do a fully general search, ie. have a dropdown of all fields and choose which to search by)

I of course said "yeah definitely" - plus "would you be ok to make a suggested list, say in a gdoc, and put it here [initially meaning #p-eahub on Slack, though github might be better] for comment?" But this is the 2.0, less basic version of search which I've created a new issue for: https://github.com/tog22/eahub/issues/21

**Comment by tog22** [comment]
@wrsaunde I'm guessing your new job is rightfully your priority right now! When do you think it'll allow you time to fit some EA work like this in?

**Comment by william-r-s** [comment]
Whoops, sorry about that! I might try to wrap up the pieces I've left
hanging next weekend, I'll see how things go.

**Comment by tog22** [comment]
Yay :smile: . That would be perfect, but it can always wait another week or two if you need to prioritise the new job. Hope it's going well!

**Comment by william-r-s** [comment]
Okay, let's actually wrap this up (sorry about leaving this hanging).
I think that there should be a link on the following pages:
http://effectivealtruismhub.com/user/profiles/all/alphabetical - somewhere prominent, at top and/or above the block of EA profiles on the page
http://effectivealtruismhub.com/user/profiles - button at the top of the page
http://effectivealtruismhub.com/user/profiles/full/pictures - button at the top of the page
http://effectivealtruismhub.com/user/profiles/all/pictures - button at the top of the page (not sure if it's the exact same page as the previous one, I'll make sure it shows up on both).

Let me know if there's anywhere else it should go.

**Comment by tog22** [comment]
Sounds good! You can add simple buttons like that directly to the live site. (Feel the power/community control! :battery: )

**Comment by william-r-s** [comment]
Done.
